project_id = "tnnzihuszaosnyeyceed"

[functions.send-sms]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.generate-document]
verify_jwt = true

[functions.send-signature-request]
verify_jwt = true

[functions.execute-automations]
verify_jwt = false

[functions.automation-webhook]
verify_jwt = false

[functions.get-signature-document]
verify_jwt = false
